"""
Preset texts and a helper to build writer instructions for SMB Decision Briefs.

Functions:
- writer_instructions(template: str, biz: str, location: str, industry_ctx=None) -> str
"""
from typing import Optional

TEMPLATES: dict[str, str] = {
    "Competitor Snapshot": (
        "Top 5 local competitors near {location}. Pricing, offers, and site SEO notes. "
        "End with 5 actions for the next 14 days."
    ),
    "Local SEO Audit": (
        "Audit {biz} in {location}: NAP consistency, priority keywords, Google Business Profile, "
        "citations, and site speed. Prioritize fixes by effort and impact."
    ),
    "Grant Opportunities": (
        "Active grants for {biz} in {location}: eligibility, deadlines, award sizes, and a prep checklist."
    ),
}

def writer_instructions(template: str, biz: str, location: str, industry_ctx=None) -> str:
    ctx = TEMPLATES[template].format(biz=biz, location=location)
    
    # Extract industry context if provided
    industry = industry_ctx.industry if industry_ctx else "business"
    subindustry = industry_ctx.subindustry if industry_ctx else "services"
    excluded_industries = industry_ctx.excluded_industries if industry_ctx else []
    
    return (
        f"SMB Decision Brief.\n\n"
        f"Context: {ctx}\n"
        f"CRITICAL: The business '{biz}' operates in the {subindustry} industry. Generate ALL content (actions, competitors, tools, gaps) for THIS industry, NOT the template type.\n"
        f"Industry: {industry}\n"
        f"Subindustry: {subindustry}\n"
        f"Location: {location}\n\n"
        "REQUIRED ACTION FORMAT (everything on ONE line):\n"
        "Action — KPI: <metric> Target: +X% in <14/30/60/90> days (Effort:L/M/H; Impact:L/M/H) | HOW: 1) <step> 2) <step> 3) <step> 4) <step> | TOOLS: 1) <tool> 2) <tool> 3) <tool> (ordered by market share/brand recognition)\n\n"
        "ACTION TITLE RULES:\n"
        "- Every action title MUST be descriptive and contain at least ONE subindustry-specific term\n"
        "- FORBIDDEN: Generic titles like 'Action', 'Update website', 'Launch campaign', 'Improve service', 'Conduct analysis', 'Evaluate offerings', 'Assess strategies', 'Comprehensive competitor pricing analysis'\n"
        "- REQUIRED: Specific subindustry service/product/capability + action verb\n"
        "- VALIDATION: Before outputting, check each action title - if it could apply to ANY industry, it's WRONG. Rewrite it with subindustry-specific terms.\n"
        "- PATTERN EXAMPLES (guides, not templates): \n"
        "  Legal/Bankruptcy→'Audit Chapter 7/13 intake workflow for local SEO' (NOT 'Conduct competitor analysis')\n"
        "  Electrical/EV→'Optimize GBP for EV charger installation searches' (NOT 'Evaluate service offerings')\n"
        "  Restaurant→'Implement OpenTable for weekend brunch reservations' (NOT 'Assess market positioning')\n\n"
        "HOW STEPS REQUIREMENTS:\n"
        "HOW steps MUST integrate tool references inline using this format: 'Use [tool category] (like ToolName) to [specific action with subindustry context]'\n\n"
        "BAD (generic, no tools): '1) Conduct audit 2) Identify gaps 3) Optimize content 4) Implement changes'\n"
        "BAD (generic tools, no subindustry context): '1) Use competitor analysis tools (like SimilarWeb) to gather pricing data 2) Use spreadsheet software (like Excel) to organize'\n\n"
        "GOOD PATTERNS (guides, not templates - adapt to ANY subindustry):\n"
        "- Legal/Bankruptcy: '1) Use practice management software (like Clio or MyCase) to audit current client intake workflow and identify ABA compliance gaps 2) Use legal content platforms (like Nolo) to create Chapter 7 vs Chapter 13 comparison chart with local court filing fees'\n"
        "- Electrical/EV: '1) Use field service management software (like ServiceTitan or Jobber) to analyze current scheduling data and identify weekend availability gaps 2) Use website plugins (like WPForms with EV calculator) to build EV charger installation cost estimator'\n"
        "- Restaurant: '1) Use POS analytics (like Toast or Square Dashboard) to identify peak ordering times and staff scheduling gaps 2) Use reservation platforms (like OpenTable) to implement waitlist management for weekend brunch'\n\n"
        "Requirements for each HOW step:\n"
        "- Start with 'Use [tool category]'\n"
        "- Provide specific tool example in parentheses '(like ToolName)'\n"
        "- Include subindustry-specific action with concrete details (not generic verbs like 'gather', 'organize', 'analyze', 'summarize')\n"
        "- Tools mentioned inline should align with the 3 tools listed in TOOLS section\n"
        "- VALIDATION: If a HOW step could apply to any industry, it's too generic - rewrite with subindustry-specific details\n\n"
        "TOOLS DISCOVERY PROCESS:\n"
        "Recommend 3 tools ordered by market share/brand recognition FOR THE SPECIFIC INDUSTRY in {location}.\n\n"
        "DISCOVERY THINKING (internal):\n"
        "1. What is the PRIMARY operational workflow for this industry? (Legal→case/client management; Electrical→service dispatch/scheduling; Restaurant→order management/reservations)\n"
        "2. What software category dominates this workflow? (Legal→practice management; Electrical/HVAC/Plumbing→field service management; Restaurant→POS systems)\n"
        "3. What are the TOP 3 brands by market share in this category? (Use your knowledge of industry-standard tools)\n\n"
        "CRITICAL RULES:\n"
        "- AVOID generic marketing tools (SEMrush, Hootsuite, Canva, Mailchimp, Facebook Ads) UNLESS the action is explicitly about marketing/advertising/social media campaigns\n"
        "- AVOID generic analysis tools (SimilarWeb, Excel, Google Sheets, Statista) UNLESS the action is explicitly about competitive analysis AND no subindustry-specific tool exists\n"
        "- FORBIDDEN: Do NOT use company names as tools. If you see a company name in search results (e.g., 'EvolveNova', 'Corporate Marketing', 'Identite Marketing'), it is a COMPETITOR, not a tool. Use actual software tools instead.\n"
        "- FORBIDDEN: Do NOT confuse competitors with tools. Tools are software platforms (Clio, ServiceTitan, Toast). Competitors are businesses (law firms, electricians, restaurants).\n"
        "- For website/SEO actions: Use Google Business Profile, Google Search Console, Ahrefs, Screaming Frog\n"
        "- For operations/CRM actions: Use subindustry-specific operational tools, NOT generic CRMs like HubSpot\n"
        "- VALIDATION: Before outputting, check each tool - if it's generic (works for any industry), ask 'Is there a subindustry-specific alternative?' If yes, use that instead.\n"
        "- VALIDATION: Before outputting, verify each tool is actual software (not a company name from competitors list). If it's a company name, replace it with appropriate software tool.\n"
        "- If uncertain: Describe the tool category + add '(top-rated {subindustry} [category] tool in {location})' as third option\n\n"
        "EXAMPLE PATTERNS (guides, not rigid templates - apply thinking to ANY industry):\n"
        "- Legal practice → Clio, MyCase, PracticePanther\n"
        "- Electrical/HVAC/Plumbing service → ServiceTitan, Jobber, FieldEdge\n"
        "- Restaurant → Toast, Square, Clover\n"
        "- Dental practice → Dentrix, Eaglesoft, Open Dental\n"
        "- Auto repair → Shop-Ware, Mitchell 1, Tekmetric\n\n"
        "Action Board (7/30/90):\n"
        "- Next 7 Days\n"
        "- Next 30 Days\n"
        "- Next 90 Days\n\n"
        "RULES:\n"
        "- FIRST 7-day action must be foundational (audit, baseline, tool access).\n"
        "- Every action MUST include HOW (4+ numbered steps with tool references inline) and TOOLS (3 industry-appropriate tools) — missing either makes it incomplete.\n"
        f"- All recommendations for {biz} only (no Owner prefixes).\n"
        "- Tie each action to competitor positioning or market opportunity.\n\n"
        "Executive summary: 4–6 bullets. Write like an industry analyst for the local market. Each bullet MUST mention {location} explicitly.\n\n"
        "HARD REQUIREMENT: At least ONE bullet must reference a UNIQUE local factor beyond generic 'growth' or 'seasonal trends'. Consider:\n"
        "- Economic drivers (major employers, industries, tourism, military base, university, government facilities)\n"
        "- Demographics (median income, homeownership rate, age distribution, population growth)\n"
        "- Geography (coastal, desert, mountains, snow belt, flood zones, hurricane region)\n"
        "- Local regulations (zoning, licensing, permits, county-specific codes)\n"
        "- Regional events (conventions, festivals, sports seasons, academic calendars)\n\n"
        "PATTERN EXAMPLES (guides for thinking, not templates):\n"
        "- Johnson City, TN (legal): 'ETSU's 14,000-student population drives 35% of landlord-tenant cases, with inquiries spiking 60% during August move-in periods'\n"
        "- Arlington, VA (electrical): 'Federal contractors represent 40% of commercial work, requiring GSA-certified electricians for government facility projects'\n"
        "- Nashville, TN (restaurant): 'Convention center events drive 25% of downtown restaurant revenue, with 180+ event days annually creating predictable demand spikes'\n\n"
        "Standard bullets should cover: (a) quantified local growth/demand metric, (b) local trend with operational implication, (c) named tools/apps used locally, (d) competitive dynamics.\n\n"
        "Main brief: markdown sections (## headings). These are RESEARCH INSIGHTS, not action lists.\n"
        "- Show competitor specifics: pricing, ratings, services.\n"
        "- Show market dynamics: gaps, trends, benchmarks supporting the recommendations.\n"
        "- If competitor snapshot, add \"Local Competitors\" with 3–5 REAL competitor names + ★ rating + review count from search results.\n"
        f"- CRITICAL: Competitor names MUST match the exact subindustry ({subindustry}).\n"
        f"- FORBIDDEN: If {biz} is in {subindustry}, do NOT include competitors from: {', '.join(excluded_industries[:8])}.\n"
        f"- SPECIFIC EXAMPLES: If {biz} is a legal firm, EXCLUDE: marketing agencies (Identite Marketing, EvolveNova, Corporate Marketing), SEO companies, web design firms, digital marketing agencies. ONLY include: law firms, attorneys, legal services.\n"
        f"- SPECIFIC EXAMPLES: If {biz} is electrical, EXCLUDE: law firms, marketing agencies. ONLY include: electricians, electrical contractors.\n"
        "- FORBIDDEN: Placeholder names like \"ABC Electric\", \"XYZ Power\", \"Company A\", \"Business B\", \"Firm 1\", \"Competitor X\"\n"
        "- REQUIRED: Filter competitors by subindustry - only include businesses in the SAME subindustry as {biz}.\n"
        "- REQUIRED: Use actual competitor names from search results only. Extract real names from the research data you received.\n"
        "- If search results contain competitors from wrong industries, IGNORE them and only use same-subindustry competitors.\n"
        f"- If no same-subindustry competitors found, write \"No direct competitors found in search results for {subindustry} in {location}\" rather than inventing placeholders.\n"
        "- Each competitor must have a real domain if mentioned (e.g., \"Bright Electric (brightelectric.com)\" from search results, not \"ABC Electric (abcelectric.com)\")\n"
        "- VALIDATION: Before listing competitors, verify each one matches {subindustry}. If unsure, exclude it.\n"
        "WRONG Main Brief: **Audit online presence** — KPI: traffic...\n"
        "RIGHT Main Brief: Teri E. Johnson offers Chapter 7 at $338 with flexible payment plans (terijohnsonlaw.com)\n"
        "RIGHT Main Brief: Most local firms lack Saturday hours, leaving weekend demand unmet (local research)\n\n"
        "Legal vertical: avoid discounts/guarantees; tag \"(Requires licensed confirmation)\" on sensitive advice.\n\n"
        "Dogs Not Barking section: REQUIRED 2 creative market gaps + 1 net-new brainstorming idea (3 total items).\n\n"
        "APPROACH: Analyze the search results you received. Look for patterns, missing services, unmet customer needs. Think creatively about {location} geography, market dynamics, and {biz} industry patterns. What customer needs are NOT being met based on the research? What service gaps exist that competitors aren't addressing?\n\n"
        "REQUIREMENTS:\n"
        "- Exactly 2 gaps: Creative analysis of unmet customer needs or service gaps specific to {location} and {biz} industry, BASED ON THE RESEARCH DATA you received\n"
        "- Exactly 1 brainstorming: A fun, net-new concept that doesn't currently exist - something innovative that gets users thinking, inspired by the research findings\n"
        "- Each gap must reference geography/market/industry factors from your research, not generic \"lack X\"\n"
        "- NO generic phrases allowed: Do NOT write 'lack weekend availability', 'limited online booking', 'no social media presence' UNLESS you have specific local evidence (e.g., 'Only 2 of 15 competitors offer Saturday hours per Google Business listings')\n"
        "- Each gap must reference an industry-specific service, product, or operational capability\n"
        "- Brainstorming must be prefixed with \"Brainstorming:\" and describe a completely new concept/service/approach\n"
        "- DO NOT copy findings verbatim - synthesize creative insights FROM the research\n\n"
        "EXAMPLES (guides, not templates):\n"
        "- Gap (based on research): \"No competitors offer EV charger installation financing despite 40% of Arlington homeowners expressing interest (from search data)\"\n"
        "- Gap (based on research): \"ETSU's 14,000-student population creates demand for evening legal consultations, but only 2 of 12 firms offer after-hours service (from competitor analysis)\"\n"
        "- Brainstorming: \"Brainstorming: Partner with local EV dealerships to offer 'EV-ready home certification' packages that include pre-wiring and installation credits - a new service category that doesn't exist yet\"\n\n"
        "CRITICAL: Before outputting, count your Dogs Not Barking items - you must have exactly 3 (2 gaps + 1 brainstorming). Base gaps on research data, not generic assumptions.\n\n"
        "WORD QUOTAS:\n"
        "- Total output: 220–420 words\n"
        "- Action Board: Present with 5 actions\n"
        "- Executive Summary: 4–6 bullets (mandatory)\n"
        "- Dogs Not Barking: 2 gaps + 1 Brainstorming (mandatory, 3 total)\n"
        "- Main Findings: 6–10 bullets\n\n"
        "Keep total within 220–420 words. No chain-of-thought. US English. Use relative days (14, 30, 60, 90) not dates. DO NOT copy examples verbatim—use them as thinking guides.\n\n"
        "SELF-CHECK (before returning output):\n"
        "Verify ALL of the following:\n"
        f"(a) Competitor names match {subindustry} subindustry (not {', '.join(excluded_industries[:3])} or other industries)\n"
        "(b) Action titles contain subindustry-specific terms (not generic 'Conduct analysis', 'Evaluate offerings')\n"
        "(c) Tools are subindustry-appropriate (not generic SimilarWeb/Excel unless explicitly justified)\n"
        "(d) HOW steps are subindustry-specific (not generic 'gather data', 'organize findings')\n"
        "(e) Dogs Not Barking has exactly 2 gaps + 1 brainstorming tied to {location} and {subindustry}\n"
        "If ANY check fails, REVISE before returning.\n\n"
        "Example action (guide, not template):\n"
        "Update GBP holiday hours — KPI: direction requests Target: +12% in 14 days (Effort:L; Impact:M) | HOW: 1) Use Google Business Profile Manager (like Google Business Profile) to log into account and review current hours 2) Use scheduling tools (like Calendly) to identify peak request times from analytics 3) Use content management (like Google Business Profile editor) to update holiday hours and publish | TOOLS: 1) Google Business Profile 2) Google Analytics 3) Calendly\n\n"
        "Output structure (JSON):\n"
        "{\n"
        '  "short_summary": "2-3 sentence summary",\n'
        '  "markdown_report": "full brief with 7/30/90 Action Board first",\n'
        '  "follow_up_questions": ["question 1", "question 2"]\n'
        "}"
    )
