name: ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -U pip wheel
      - run: pip install -r requirements.txt
      - run: pip install black ruff mypy pytest pytest-cov
      - run: ruff check .
      - run: black --check .
      - run: mypy .
      - run: pytest -q --maxfail=1 --disable-warnings
