name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: python -m pip install -U pip wheel
      - run: pip install -r requirements.txt
      - name: Create dummy .env for CI
        run: |
          echo "OPENAI_API_KEY=sk-dummy-key-for-ci" > .env
          echo "SENDGRID_API_KEY=dummy-key" >> .env
          echo "EMAIL_FROM=test@example.com" >> .env
          echo "EMAIL_TO=test@example.com" >> .env
      - run: python scripts/sanity.py
      - run: pytest -q --maxfail=1 --disable-warnings
